project:
  type: website
  output-dir: docs

website:
  title: "Xiang Liu"
  site-url: "https://xiangliu-econ.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: personal.qmd
        text: Personal

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css